title: Asteriod: The Programming Language
description: Asteroid is a multi-paradigm, application-oriented programming language supporting first-class patterns.
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
