title: The Asteriod Programming Language
description: Asteroid is a multi-paradigm, application-oriented programming language supporting first-class patterns.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
