[package]
name = "symtab"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ast = { path = "C:/Users/Timothy/Desktop/avm/ast" }
lazy_static = "1.4.0"