coverage:
  status:
    project:
      default:
        target: "100%"
        # paths:
        #   - "src"
comment:
  layout: "diff, files"
codecov:
  disable_default_path_fixes: false

# fixes:
#   - "::src/"
# fixes:
#   - "src/::"
